version: 0.2
run-as: yoctouser

env:
  shell: bash

phases:
  pre_build:
    commands:
      - git submodule update --init --recursive
      - chown -R yoctouser /sstate-cache
  build:
    commands:
      - echo Build started on `date`
      - . ./init-build-env $TMP_DIR
      - BUILD_DEVICE=qemu bitbake core-image-minimal
  post_build:
    commands:
      - echo Build completed on `date`
      - ps aux | grep bitbake
      - find $TMP_DIR -name '*.socket' -delete
