version: 0.2
run-as: yoctouser

env:
  shell: bash

phases:
  build:
    commands:
      - echo Test started on `date`
      - ls -lha build-output
      - ls -lha /build-output
      - tar xvf "/build-output/$(cat build-output/tmpfile)"
  post_build:
    commands:
      - echo Test completed on `date`
