name: Linting
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
jobs:
  Run-Pre-Commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Pre-Commit
        run: pip install pre-commit
      - name: Run Pre-Commit
        run: pre-commit run --all-files --color=always --show-diff-on-failure
